### ISSUE TITLE
Broken tests (tracking issue)

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1677]
Bug to track which tests are currently broken (feel free to edit)

- [ ] #1501 tests/MMS/fieldalign
- [ ] #1500 tests/MMS/tokamak
- [ ] #1502 tests/MMS/GBS
- [ ] #1507 examples/elm-pb
- [ ] #1675 examples/invertable_operator
- [ ] #1676 tests/integrated/test-datadir

**Comment by bshanahan** [comment]
Just to add: 
both fci-wave and fci-wave-logn require tokamak.fci.nc, but this is not included, nor is the script used to generate it.
